---

- name: Check created disk
  stat:
    path: "{{ item.device }}"
  loop: "{{ iscsi_backstores }}"
  register: disk_check

- name: Check all disks
  assert:
    that: 
      - item.stat.exists
    fail_msg: "Диск {{ item.item.device }} не найден"
  loop: "{{ disk_check.results }}"
  loop_control:
    label: "{{ item.item.device }}"

- name: Check existing backstores
  shell: targetcli /backstores/block ls
  register: existing_backstores
  changed_when: false
  tags: [config]

- name: Create block backstore
  shell: |
    targetcli /backstores/block create name={{ item.name }} dev={{ item.device }}
  loop: "{{ iscsi_backstores }}"
  when: item.name not in existing_backstores.stdout
  loop_control:
    label: "{{ item.name }}"

- name: Create iSCSI target
  shell: |
    targetcli /iscsi create {{ item.iqn }}
  loop: "{{ iscsi_targets }}"
  register: target_result
  changed_when: item.iqn in target_result.stdout
  failed_when:
    - "'already exists' not in target_result.stderr"
    - "target_result.rc != 0"

- name: Check LUNs
  shell: targetcli /iscsi/{{ item.iqn }}/tpg1/luns ls
  loop: "{{ iscsi_targets }}"
  loop_control:
    loop_var: item
  register: existing_luns
  changed_when: false
  failed_when: false

- name: Create LUNs for target
  shell: |
    targetcli /iscsi/{{ item.iqn }}/tpg1/luns create /backstores/block/{{ bs }}
  loop: "{{ iscsi_targets }}"
  loop_control:
    loop_var: item
  vars:
    bs: "{{ item.backstores[0] }}"
  register: luns_result
  ignore_errors: true
  tags: [config]

- name: Check Luns Error
  fail:
    msg: "Ошибка создания LUN для {{ item.item.iqn }}: {{ item.stderr }}"
  loop: "{{ luns_result.results }}"
  when: 
    - item.failed | default(false)
    - "'already exists' not in item.stderr"
  loop_control:
    label: "{{ item.item.iqn }}"
  tags: [config]

- name: Create ACL
  shell: |
    targetcli /iscsi/{{ item.0.iqn }}/tpg1/acls create {{ item.1 }}
  loop: "{{ iscsi_targets | subelements('initiators') }}"
  loop_control:
    label: "{{ item.0.iqn }} -> {{ item.1 }}"
  register: acl_results
  failed_when: false
  ignore_errors: true

- name: Check Error ACL
  fail:
    msg: "Ошибка ACL {{ item.item.0.iqn }} -> {{ item.item.1 }}: {{ item.stderr }}"
  loop: "{{ acl_results.results }}"
  when:
    - item.rc != 0
    - "'already exists' not in item.stderr"
    - "'Created' not in item.stderr"
  loop_control:
    label: "{{ item.item.0.iqn }} -> {{ item.item.1 }}"
  
- name: Save config 
  shell: targetcli / saveconfig