---

iscsi_target_packages: 
  - targetcli-fb

iscsi_initiator_packages:
  - open-iscsi

iscsi_gfs_packages:
  - lvm2
  - lvm2-lockd
  - dlm-controld
  - gfs2-utils
  - pacemaker
  - corosync 
  - pcs