---

- name: Check created disk
  stat:
    path: "{{ item.device }}"
  loop: "{{ iscsi_backstores }}"
  register: disk_check

- name: Check all disks
  assert:
    that: 
      - item.stat.exists
    fail_msg: "Диск {{ item.item.device }} не найден"
  loop: "{{ disk_check.results }}"
  loop_control:
    label: "{{ item.item.device }}"

- name: Check existing backstores
  shell: targetcli /backstores/block ls
  register: existing_backstores
  changed_when: false
  tags: [config]

# 2. Создаём только если нет
- name: Create block backstore
  shell: |
    targetcli /backstores/block create name={{ item.name }} dev={{ item.device }}
  loop: "{{ iscsi_backstores }}"
  when: item.name not in existing_backstores.stdout
  loop_control:
    label: "{{ item.name }}"

- name: Create iSCSI target
  shell: |
    targetcli /iscsi create {{ item.iqn }}
  loop: "{{ iscsi_targets }}"
  register: target_result
  changed_when: item.iqn in target_result.stdout
  failed_when:
    - "'already exists' not in target_result.stderr"
    - "target_result.rc != 0"

- name: Create LUNs for target
  shell: |
    targetcli /iscsi/{{ item.iqn }}/tpg1/luns create /backstores/block/{{ bs }}
  loop: "{{ iscsi_targets }}"
  loop_control:
    loop_var: item
  vars:
    bs: "{{ item.backstores[0] }}"
  register: luns_result
  changed_when: "'Created' in item.stderr"

- name: Create ACL for initiator
  shell: |
    targetcli /iscsi/{{ item.iqn }}/tpg1/acls create {{ initiator }}
  loop: "{{ iscsi_targets }}"
  loop_control:
    loop_var: item
  vars: 
    initiator: "{{ item.initiators[0] }}"