---

- name: Check created disk
  stat:
    path: "{{ item.device }}"
  loop: "{{ iscsi_backstores }}"
  register: disk_check

- name: Check all disks
  assert:
    that: 
      - item.stat.exists
    fail_msg: "Диск {{ item.item.device }} не найден"
  loop: "{{ disk_check.results }}"
  loop_control:
    label: "{{ item.item.device }}"

- name: Check existing backstores
  shell: targetcli /backstores/block ls
  register: existing_backstores
  changed_when: false
  tags: [config]

# 2. Создаём только если нет
- name: Create block backstore
  shell: |
    targetcli /backstores/block create name={{ item.name }} dev={{ item.device }}
  loop: "{{ iscsi_backstores }}"
  when: item.name not in existing_backstores.stdout
  loop_control:
    label: "{{ item.name }}"

- name: Create iSCSI target
  shell: |
    targetcli /iscsi create {{ item.iqn }}
  loop: "{{ iscsi_targets }}"
  register: target_result
  changed_when: item.iqn in target_result.stdout
  failed_when:
    - "'already exists' not in target_result.stderr"
    - "target_result.rc != 0"

- name: Create LUNs for target
  shell: |
    targetcli /iscsi/{{ item.iqn }}/tpg1/luns create /backstores/block/{{ bs }}
  loop: "{{ iscsi_targets }}"
  loop_control:
    loop_var: item
  vars:
    bs: "{{ item.backstores[0] }}"
  register: luns_result
  changed_when: "'Created' in item.stderr"

- name: Create ACL for initiator
  shell: |
    targetcli /iscsi/{{ item.iqn }}/tpg1/acls create {{ initiator }}
  loop: "{{ iscsi_targets }}"
  loop_control:
    loop_var: item
  vars: 
    initiator: "{{ item.initiators[0] }}"

   
    # - name: Установка пакетов для iSCSI Target
    #   package:
    #     name:
    #       - targetcli-fb
    #       - python3-rtslib
    #     state: present
    #   tags: [install]

    # - name: Создание директории для дисков
    #   file:
    #     path: /var/iscsi/disks
    #     state: directory
    #     mode: '0755'
    #   tags: [config]

    # - name: Создание файлов backstore
    #   command: "dd if=/dev/zero of={{ item.path }} bs=1M count={{ item.size | regex_replace('G', '000') }} status=progress"
    #   args:
    #     creates: "{{ item.path }}"
    #   loop: "{{ iscsi_backstores }}"
    #   tags: [config]

    # - name: Настройка iSCSI через targetcli
    #   shell: |
    #     targetcli /backstores/fileio create name={{ item.name }} file_or_dev={{ item.path }}
    #   loop: "{{ iscsi_backstores }}"
    #   register: backstore_result
    #   changed_when: "'Created fileio' in backstore_result.stdout"
    #   failed_when: "'already exists' not in backstore_result.stderr and backstore_result.rc != 0"
    #   tags: [config]

    # - name: Создание iSCSI Target
    #   shell: |
    #     targetcli /iscsi create {{ item.iqn }}
    #   loop: "{{ iscsi_targets }}"
    #   register: target_result
    #   changed_when: "'Created target' in target_result.stdout"
    #   failed_when: "'already exists' not in target_result.stderr and target_result.rc != 0"
    #   tags: [config]

    # - name: Создание LUN для Target
    #   shell: |
    #     targetcli /iscsi/{{ item.iqn }}/tpg1/luns create /backstores/fileio/{{ bs }}
    #   loop: "{{ iscsi_targets }}"
    #   loop_control:
    #     loop_var: item
    #   vars:
    #     bs: "{{ item.backstores[0] }}"
    #   tags: [config]

    # - name: Настройка ACL для инициаторов
    #   shell: |
    #     targetcli /iscsi/{{ item.iqn }}/tpg1/acls create {{ initiator }}
    #   loop: "{{ iscsi_targets }}"
    #   loop_control:
    #     loop_var: item
    #   vars:
    #     initiator: "{{ item.initiators[0] }}"
    #   tags: [config]

    # - name: Сохранение конфигурации targetcli
    #   shell: targetcli / saveconfig
    #   tags: [config]

    # - name: Включение и запуск службы target
    #   service:
    #     name: target
    #     enabled: true
    #     state: started
    #   tags: [service]

    # - name: Открытие порта в firewall
    #   firewalld:
    #     port: "{{ iscsi_port }}/tcp"
    #     permanent: true
    #     immediate: true
    #   when: ansible_facts['distribution'] in ['RedHat', 'CentOS', 'AlmaLinux', 'Rocky']
    #   tags: [firewall]