--- 
iscsi_dir: /var/iscsi/disks

iscsi_backstores:
  - name: disk1
    device: /dev/sdb 

iscsi_targets:
  - iqn: "iqn.2026-05.iscsi.pilot:storage.target00"
    backstores: [disk1]
    initiators:
      - iqn.2026-05.iscsi.pilot:gfs-node-1:client1
      - iqn.2026-05.iscsi.pilot:gfs-node-2:client2
      - iqn.2026-05.iscsi.pilot:gfs-node-3:client3

iscsi_iqn_prefix: "iqn.2026-05.iscsi.pilot"

initiator_iqn: "{{ iscsi_iqn_prefix }}:{{ inventory_hostname }}:client{{ inventory_hostname.split('-')[-1] }}"
iscsi_target_standalone: iqn.2026-05.iscsi.pilot:storage.target00
iscsi_target_ip: "192.168.1.32"