---

- name: Install packages iscsi-target
  hosts: all
  become: true
  roles:
    - ../roles/preinstall
  tags:
    - install

- name: Create iscsi-target
  hosts: iscsi-target
  become: true
  roles:
    - ../roles/create-iscsi-target
  tags:
    - target

- name: Connect iscsi-initiator
  hosts: gfs-nodes
  become: true
  roles:
    - ../roles/connect-iscsi-initiator
  tags:
    - initiator

- name: Setup corosync
  hosts: gfs-nodes #TO-DO: Выбор мастера на котором сделаются GFS-разделы
  become: true
  roles:
    - ../roles/setup-corosync
  tags:
    - corosync
    - cluster

- name: Setup dlm
  hosts: gfs-nodes #TO-DO: Выбор мастера на котором сделаются GFS-разделы
  become: true
  roles:
    - ../roles/setup-dlm
  tags:
    - dlm
    - cluster

- name: Setup corosync
  hosts: gfs-nodes #TO-DO: Выбор мастера на котором сделаются GFS-разделы
  become: true
  roles:
    - ../roles/pacemaker-setup
  tags:
    - pacemaker
    - cluster

- name: Create LVM cluster
  hosts: gfs-node-1 #TO-DO: Выбор мастера на котором сделаются GFS-разделы
  become: true
  roles:
    - ../roles/create-lvm-cluster
  tags:
    - lvm
    - cluster
  